name: Docker Image CI

on:
  push:
    branches: [ master, dev ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          repository: fluktuid/you-asked-for
          push: true
          tags: $BRANCH_NAME
