name: Docker Image CI

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          repository: fluktuid/you-asked-for
          push: false
